#!/usr/bin/env bash
#
# This script implements the release workflow for helm charts.
#

usage() {
    cat<<EOF
usage:
 if on master branch: release pre|rc <chart>
if on release branch: release major|minor|patch|pre <chart>

where:
  <chart> is the name of the chart
EOF
}

HELM_REPO=${HELM_REPO:-cm://h.cfcr.io/scispike/$CHART}

if [ -n "$HELM_REPO_ACCESS_TOKEN" ]; then
  HELM_REPO_ACCESS_TOKEN_ARG="--access-token '$HELM_REPO_ACCESS_TOKEN'"
fi
ADDITIONAL_PUSH_ARGS="$ADDITIONAL_PUSH_ARGS $HELM_REPO_ACCESS_TOKEN_ARG"

if [ -n "$TEST" ]; then ECHO=echo; fi
if [ -n "$DBG" ]; then set -x; fi

ORIGIN=${ORIGIN:-origin}
MASTER=${MASTER:-master}

RELEASE_LEVEL="$1"
case "$RELEASE_LEVEL" in
  major|minor|patch|pre|rc)
    # ok
    ;;
  h|he|hel|help)
    usage
    exit 0
    ;;
  *)
    echo "ERROR: Specify release level of 'pre', 'patch', 'minor', 'major', or 'rc'" >&2
    usage
    exit 1
    ;;
esac

CHART=$2
if [ -z "$CHART" ]; then
  echo "ERROR: no chart name given"
  usage
  exit 1
fi
CHART=${CHART%/}

git pull

if ! git diff --exit-code --no-patch; then
  echo 'ERROR: You have modified tracked files; only release from clean directories!' >&2
  exit 3
fi

if ! git diff --cached --exit-code --no-patch; then
  echo 'ERROR: You have cached modified tracked files; only release from clean directories!' >&2
  exit 3
fi

if [ -n "$(git status -s)" ]; then
  echo 'ERROR: You have unignored untracked files; only release from clean directories!' >&2
  exit 3
fi

VERSION="$(cat $CHART/Chart.yaml | docker run --rm -i matthewadams12/ymlx this.version)"
if [[ ! "$VERSION" =~ \-(pre|rc)\.[0-9]{1,}$ ]]; then
  echo 'ERROR: repository is in an inconsistent state: version does NOT end in a prerelease suffix!' >&2
  exit 3
fi

BRANCH="$(git status | head -n 1 | awk '{ print $3 }')"
if [[ ! "$BRANCH" =~ ^(master|v[0-9]{1,}\.[0-9]{1,})$ ]]; then # it is not a master or a release branch
  echo 'ERROR: You can only release from the master branch or release branches (vmajor.minor)!' >&2
  exit 3
fi

if ! git diff --exit-code -no-patch $BRANCH $ORIGIN/$BRANCH; then
  echo "ERROR: Local branch $BRANCH differs from remote branch $ORIGIN/$BRANCH" >&2
  exit 3
fi

if [ "$BRANCH" == "$MASTER" ]; then
  case "$RELEASE_LEVEL" in
    pre|rc)
      # ok
      ;;
    *)
      echo "ERROR: Only 'pre' or 'rc' releases are permitted from the $MASTER branch." >&2
      exit 6
      ;;
  esac
else # this is a release branch
  case "$RELEASE_LEVEL" in
      pre|patch|minor|major)
        # ok
        ;;
      *)
        echo "ERROR: Only 'pre', 'patch', 'minor', or 'major' releases are permitted from a release branch." >&2
        exit 7
        ;;
  esac
fi

if [ "$BRANCH" == "$MASTER" ]; then
  if [[ ! "$VERSION" =~ ^([0-9]{1,})\.([0-9]{1,})\.0\-pre\.([0-9]{1,})$ ]]; then
    echo "ERROR: The version does not match the format of major.minor.0-pre.n required in the $MASTER branch." >&2
    exit 8
  fi

  # create release branch
  MAJOR=${BASH_REMATCH[1]}
  MINOR=${BASH_REMATCH[2]}
  PATCH=0
  PRE=${BASH_REMATCH[3]}

  case "$RELEASE_LEVEL" in
  rc) # then it's time to create a new release branch
      NEW_RELEASE_BRANCH="v$MAJOR.$MINOR"
      git checkout -b $NEW_RELEASE_BRANCH

      NEW_RELEASE_BRANCH_VERSION="$MAJOR.$MINOR.0-rc.0"

      CHART_CONTENT="$(cat $CHART/Chart.yaml)"
      echo -n "$CHART_CONTENT" \
        | docker run --rm -i matthewadams12/ymlx "it => { it.version = '$NEW_RELEASE_BRANCH_VERSION'; return it; }" \
        > $CHART/Chart.yaml

      git add .
      git commit -m "release $NEW_RELEASE_BRANCH_VERSION"
      git tag $NEW_RELEASE_BRANCH_VERSION
      git push -u $ORIGIN $NEW_RELEASE_BRANCH
      git push --tags

      # return to master branch
      git checkout $MASTER
      git cherry-pick $NEW_RELEASE_BRANCH # cherry pick from release branch to get release candidate commit in master
      # advance master version
      NEXT_VERSION="$MAJOR.$(($MINOR+1)).0-pre.0"

      CHART_CONTENT="$(cat $CHART/Chart.yaml)"
      echo -n "$CHART_CONTENT" \
        | docker run --rm -i matthewadams12/ymlx "it => { it.version = '$NEXT_VERSION'; return it; }" \
        > $CHART/Chart.yaml

      git add .
      git commit -m "bump to $NEXT_VERSION [skip ci]"
      git push

      # return to release branch & prepare for next prerelease
      git checkout $NEW_RELEASE_BRANCH
      NEXT_RELEASE_BRANCH_VERSION="$MAJOR.$MINOR.0-rc.1"

      CHART_CONTENT="$(cat $CHART/Chart.yaml)"
      echo -n "$CHART_CONTENT" \
        | docker run --rm -i matthewadams12/ymlx "it => { it.version = '$NEXT_RELEASE_BRANCH_VERSION'; return it; }" \
        > $CHART/Chart.yaml

      git add .
      git commit -m "bump to $NEXT_RELEASE_BRANCH_VERSION [skip ci]"
      git push

      echo "tagged $NEW_RELEASE_BRANCH_VERSION for release"
      exit 0
      ;;

  pre)
      git tag "v$VERSION"
      RELEASED_VERSION="$VERSION"
      NEXT_VERSION=$MAJOR.$MINOR.$PATCH-pre.$((PRE+1))

      CHART_CONTENT="$(cat $CHART/Chart.yaml)"
      echo -n "$CHART_CONTENT" \
        | docker run --rm -i matthewadams12/ymlx "it => { it.version = '$NEXT_VERSION'; return it; }" \
        > $CHART/Chart.yaml

      git add .
      git commit -m "bump to $VERSION [skip ci]"
      git push
      git push --tags
      echo "tagged $RELEASED_VERSION for release"
      exit 0
      ;;
  esac
fi

# If we get this far, we are releasing something from a release branch.

if [[ ! "$VERSION" =~ ^([0-9]{1,})\.([0-9]{1,})\.([0-9]{1,})\-rc\.([0-9]{1,})$ ]]; then
  echo "ERROR: The version does not match the format of major.minor.patch-rc.n required in the release branch." >&2
  exit 8
fi
MAJOR=${BASH_REMATCH[1]}
MINOR=${BASH_REMATCH[2]}
PATCH=${BASH_REMATCH[3]}
PRE=${BASH_REMATCH[4]}

case "$RELEASE_LEVEL" in
  major|minor|patch)

    # NOTE: if RELEASE_LEVEL is 'minor' & we're prepped for a major release, no harm, no foul.
    # A major release is the same as a minor release, only that the minor version is 0.

    if [ $RELEASE_LEVEL == major ] && [ $MINOR != 0 ]; then
      echo "ERROR: This branch is not prepared for a major release because the minor version is $MINOR, not 0." >&2
      exit 10
    else
      NEXT_RELEASE_BRANCH_VERSION="$MAJOR.$MINOR.1-rc.0"
    fi
    if [ $RELEASE_LEVEL == minor ] && [ $PATCH != 0 ]; then
      echo "ERROR: A minor release has already been performed in this branch; only patch releases are allowed now in this release branch." >&2
      exit 11
    else
      NEXT_RELEASE_BRANCH_VERSION="$MAJOR.$MINOR.1-rc.0"
    fi
    if [ $RELEASE_LEVEL == patch ] && [ $PATCH == 0 ]; then
      echo "ERROR: You must release a minor release before releasing a patch in this release branch." >&2
      exit 12
    else
      NEXT_RELEASE_BRANCH_VERSION="$MAJOR.$MINOR.$((PATCH+1))-rc.0"
    fi

    RELEASE_VERSION="$MAJOR.$MINOR.$PATCH"

    CHART_CONTENT="$(cat $CHART/Chart.yaml)"
    echo -n "$CHART_CONTENT" \
      | docker run --rm -i matthewadams12/ymlx "it => { it.version = '$RELEASE_VERSION'; return it; }" \
      > $CHART/Chart.yaml

    git add .
    git commit -m "release $RELEASE_VERSION"
    git tag "v$RELEASE_VERSION"
    git push
    git push --tags

    CHART_CONTENT="$(cat $CHART/Chart.yaml)"
    echo -n "$CHART_CONTENT" \
      | docker run --rm -i matthewadams12/ymlx "it => { it.version = '$NEXT_RELEASE_BRANCH_VERSION'; return it; }" \
      > $CHART/Chart.yaml

    git add .
    git commit -m "bump to $NEXT_RELEASE_BRANCH_VERSION [skip ci]"
    git push
    echo "tagged $RELEASED_VERSION"
    exit 0
    ;;

  rc)
    git tag "v$VERSION"

    NEXT_RELEASE_BRANCH_VERSION="$MAJOR.$MINOR.$PATCH-rc.$((PRE+1))"

    CHART_CONTENT="$(cat $CHART/Chart.yaml)"
    echo -n "$CHART_CONTENT" \
      | docker run --rm -i matthewadams12/ymlx "it => { it.version = '$NEXT_RELEASE_BRANCH_VERSION'; return it; }" \
      > $CHART/Chart.yaml

    git add .
    git commit -m "bump to $NEXT_RELEASE_BRANCH_VERSION [skip ci]"
    git push
    git push --tags
    echo "tagged v$VERSION"
    exit 0
    ;;
esac
